apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sales-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      name: sales-api
      labels:
        service: sales-api
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.11
        ports:
        - name: zipkin
          containerPort: 9411
        resources: {}
      - name: sales-api
        image: gcr.io/sales-api/sales-api-amd64:1.0
        env:
        - name: SALES_TRACE_HOST
          value: "http://localhost:3002/v1/publish"
        - name: SALES_AUTH_KEY_ID
          value: "1"
        ports:
        - name: sales-api
          containerPort: 3000
        - name: debug
          containerPort: 4000
        resources: {}
      - name: metrics
        image: gcr.io/sales-api/metrics-amd64:1.0
        env:
        - name: METRICS_COLLECT_FROM
          value: "http://localhost:4000/debug/vars"
        ports:
        - name: metrics
          containerPort: 3001
        - name: debug
          containerPort: 4001
        resources: {}
      - name: tracer
        image: gcr.io/sales-api/tracer-amd64:1.0
        env:
        - name: TRACER_ZIPKIN_HOST
          value: "http://localhost:9411/api/v2/spans"
        ports:
        - name: tracer
          containerPort: 3002
        - name: debug
          containerPort: 4002
        resources: {}
status: {}
