iface: lo0
insecureSkipVerify: true
contexts:
  - name: ardan-service
    enabled: true
    url: ws://localhost:18081
    enableportforward: true
    runtime:
      kubeconfig: ~/.kube/config # defaults to ~/.kube/config
      kubecontext: default # defaults to defaul in kubeconfig
      kubenamespace: netmux # defaults to netmux
      kubeinstance: netmux # defaults to netmux - consider using a dedicated