apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vault/
images:
- name: metrics-image
  newName: metrics
  newTag: "1.0"
- name: sales-api-image
  newName: sales-api
  newTag: "1.0"
