apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  labels:
    app.kubernetes.io/name: sales
    app.kubernetes.io/component: service
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sales
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sales
    spec:
      containers:
      - name: sales
        image: ardanlabs/service-sales:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: SALES_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: SALES_DB_PORT
          value: "5432"
        - name: SALES_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SALES_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: SALES_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
