[serviceweaver]
binary = "./sales-api"
rollout = "5m"

[single]
listeners.api   = {address = "localhost:3000"}
listeners.debug = {address = "localhost:4000"}

[multi]
listeners.api   = {address = "localhost:3000"}
listeners.debug = {address = "localhost:4000"}