apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod
  namespace: sales-system
spec:

  # Use two replicas in a production environment to allow for rolling updates of the service.
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: sales-api

        # Give Kubernetes enough time to stop sending traffic to the Pod while it is shutting down.
        # https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - "sleep 5"
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  type: LoadBalancer
