export default [
  { value: "AF", title: "Afghanistan" },
  { value: "AL", title: "Albania" },
  { value: "DZ", title: "Algeria" },
  { value: "AS", title: "American Samoa" },
  { value: "AD", title: "Andorra" },
  { value: "AO", title: "Angola" },
  { value: "AI", title: "Anguilla" },
  { value: "AQ", title: "Antarctica" },
  { value: "AG", title: "Antigua and Barbuda" },
  { value: "AR", title: "Argentina" },
  { value: "AM", title: "Armenia" },
  { value: "AW", title: "Aruba" },
  { value: "AU", title: "Australia" },
  { value: "AT", title: "Austria" },
  { value: "AZ", title: "Azerbaijan" },
  { value: "BS", title: "Bahamas (the)" },
  { value: "BH", title: "Bahrain" },
  { value: "BD", title: "Bangladesh" },
  { value: "BB", title: "Barbados" },
  { value: "BY", title: "Belarus" },
  { value: "BE", title: "Belgium" },
  { value: "BZ", title: "Belize" },
  { value: "BJ", title: "Benin" },
  { value: "BM", title: "Bermuda" },
  { value: "BT", title: "Bhutan" },
  { value: "BO", title: "Bolivia (Plurinational State of)" },
  { value: "BQ", title: "Bonaire, Sint Eustatius and Saba" },
  { value: "BA", title: "Bosnia and Herzegovina" },
  { value: "BW", title: "Botswana" },
  { value: "BV", title: "Bouvet Island" },
  { value: "BR", title: "Brazil" },
  { value: "IO", title: "British Indian Ocean Territory (the)" },
  { value: "BN", title: "Brunei Darussalam" },
  { value: "BG", title: "Bulgaria" },
  { value: "BF", title: "Burkina Faso" },
  { value: "BI", title: "Burundi" },
  { value: "CV", title: "Cabo Verde" },
  { value: "KH", title: "Cambodia" },
  { value: "CM", title: "Cameroon" },
  { value: "CA", title: "Canada" },
  { value: "KY", title: "Cayman Islands (the)" },
  { value: "CF", title: "Central African Republic (the)" },
  { value: "TD", title: "Chad" },
  { value: "CL", title: "Chile" },
  { value: "CN", title: "China" },
  { value: "CX", title: "Christmas Island" },
  { value: "CC", title: "Cocos (Keeling) Islands (the)" },
  { value: "CO", title: "Colombia" },
  { value: "KM", title: "Comoros (the)" },
  { value: "CD", title: "Congo (the Democratic Republic of the)" },
  { value: "CG", title: "Congo (the)" },
  { value: "CK", title: "Cook Islands (the)" },
  { value: "CR", title: "Costa Rica" },
  { value: "HR", title: "Croatia" },
  { value: "CU", title: "Cuba" },
  { value: "CW", title: "Curaçao" },
  { value: "CY", title: "Cyprus" },
  { value: "CZ", title: "Czechia" },
  { value: "CI", title: "Côte d'Ivoire" },
  { value: "DK", title: "Denmark" },
  { value: "DJ", title: "Djibouti" },
  { value: "DM", title: "Dominica" },
  { value: "DO", title: "Dominican Republic (the)" },
  { value: "EC", title: "Ecuador" },
  { value: "EG", title: "Egypt" },
  { value: "SV", title: "El Salvador" },
  { value: "GQ", title: "Equatorial Guinea" },
  { value: "ER", title: "Eritrea" },
  { value: "EE", title: "Estonia" },
  { value: "SZ", title: "Eswatini" },
  { value: "ET", title: "Ethiopia" },
  { value: "FK", title: "Falkland Islands (the) [Malvinas]" },
  { value: "FO", title: "Faroe Islands (the)" },
  { value: "FJ", title: "Fiji" },
  { value: "FI", title: "Finland" },
  { value: "FR", title: "France" },
  { value: "GF", title: "French Guiana" },
  { value: "PF", title: "French Polynesia" },
  { value: "TF", title: "French Southern Territories (the)" },
  { value: "GA", title: "Gabon" },
  { value: "GM", title: "Gambia (the)" },
  { value: "GE", title: "Georgia" },
  { value: "DE", title: "Germany" },
  { value: "GH", title: "Ghana" },
  { value: "GI", title: "Gibraltar" },
  { value: "GR", title: "Greece" },
  { value: "GL", title: "Greenland" },
  { value: "GD", title: "Grenada" },
  { value: "GP", title: "Guadeloupe" },
  { value: "GU", title: "Guam" },
  { value: "GT", title: "Guatemala" },
  { value: "GG", title: "Guernsey" },
  { value: "GN", title: "Guinea" },
  { value: "GW", title: "Guinea-Bissau" },
  { value: "GY", title: "Guyana" },
  { value: "HT", title: "Haiti" },
  { value: "HM", title: "Heard Island and McDonald Islands" },
  { value: "VA", title: "Holy See (the)" },
  { value: "HN", title: "Honduras" },
  { value: "HK", title: "Hong Kong" },
  { value: "HU", title: "Hungary" },
  { value: "IS", title: "Iceland" },
  { value: "IN", title: "India" },
  { value: "ID", title: "Indonesia" },
  { value: "IR", title: "Iran (Islamic Republic of)" },
  { value: "IQ", title: "Iraq" },
  { value: "IE", title: "Ireland" },
  { value: "IM", title: "Isle of Man" },
  { value: "IL", title: "Israel" },
  { value: "IT", title: "Italy" },
  { value: "JM", title: "Jamaica" },
  { value: "JP", title: "Japan" },
  { value: "JE", title: "Jersey" },
  { value: "JO", title: "Jordan" },
  { value: "KZ", title: "Kazakhstan" },
  { value: "KE", title: "Kenya" },
  { value: "KI", title: "Kiribati" },
  { value: "KP", title: "Korea (the Democratic People's Republic of)" },
  { value: "KR", title: "Korea (the Republic of)" },
  { value: "KW", title: "Kuwait" },
  { value: "KG", title: "Kyrgyzstan" },
  { value: "LA", title: "Lao People's Democratic Republic (the)" },
  { value: "LV", title: "Latvia" },
  { value: "LB", title: "Lebanon" },
  { value: "LS", title: "Lesotho" },
  { value: "LR", title: "Liberia" },
  { value: "LY", title: "Libya" },
  { value: "LI", title: "Liechtenstein" },
  { value: "LT", title: "Lithuania" },
  { value: "LU", title: "Luxembourg" },
  { value: "MO", title: "Macao" },
  { value: "MG", title: "Madagascar" },
  { value: "MW", title: "Malawi" },
  { value: "MY", title: "Malaysia" },
  { value: "MV", title: "Maldives" },
  { value: "ML", title: "Mali" },
  { value: "MT", title: "Malta" },
  { value: "MH", title: "Marshall Islands (the)" },
  { value: "MQ", title: "Martinique" },
  { value: "MR", title: "Mauritania" },
  { value: "MU", title: "Mauritius" },
  { value: "YT", title: "Mayotte" },
  { value: "MX", title: "Mexico" },
  { value: "FM", title: "Micronesia (Federated States of)" },
  { value: "MD", title: "Moldova (the Republic of)" },
  { value: "MC", title: "Monaco" },
  { value: "MN", title: "Mongolia" },
  { value: "ME", title: "Montenegro" },
  { value: "MS", title: "Montserrat" },
  { value: "MA", title: "Morocco" },
  { value: "MZ", title: "Mozambique" },
  { value: "MM", title: "Myanmar" },
  { value: "NA", title: "Namibia" },
  { value: "NR", title: "Nauru" },
  { value: "NP", title: "Nepal" },
  { value: "NL", title: "Netherlands (the)" },
  { value: "NC", title: "New Caledonia" },
  { value: "NZ", title: "New Zealand" },
  { value: "NI", title: "Nicaragua" },
  { value: "NE", title: "Niger (the)" },
  { value: "NG", title: "Nigeria" },
  { value: "NU", title: "Niue" },
  { value: "NF", title: "Norfolk Island" },
  { value: "MP", title: "Northern Mariana Islands (the)" },
  { value: "NO", title: "Norway" },
  { value: "OM", title: "Oman" },
  { value: "PK", title: "Pakistan" },
  { value: "PW", title: "Palau" },
  { value: "PS", title: "Palestine, State of" },
  { value: "PA", title: "Panama" },
  { value: "PG", title: "Papua New Guinea" },
  { value: "PY", title: "Paraguay" },
  { value: "PE", title: "Peru" },
  { value: "PH", title: "Philippines (the)" },
  { value: "PN", title: "Pitcairn" },
  { value: "PL", title: "Poland" },
  { value: "PT", title: "Portugal" },
  { value: "PR", title: "Puerto Rico" },
  { value: "QA", title: "Qatar" },
  { value: "MK", title: "Republic of North Macedonia" },
  { value: "RO", title: "Romania" },
  { value: "RU", title: "Russian Federation (the)" },
  { value: "RW", title: "Rwanda" },
  { value: "RE", title: "Réunion" },
  { value: "BL", title: "Saint Barthélemy" },
  { value: "SH", title: "Saint Helena, Ascension and Tristan da Cunha" },
  { value: "KN", title: "Saint Kitts and Nevis" },
  { value: "LC", title: "Saint Lucia" },
  { value: "MF", title: "Saint Martin (French part)" },
  { value: "PM", title: "Saint Pierre and Miquelon" },
  { value: "VC", title: "Saint Vincent and the Grenadines" },
  { value: "WS", title: "Samoa" },
  { value: "SM", title: "San Marino" },
  { value: "ST", title: "Sao Tome and Principe" },
  { value: "SA", title: "Saudi Arabia" },
  { value: "SN", title: "Senegal" },
  { value: "RS", title: "Serbia" },
  { value: "SC", title: "Seychelles" },
  { value: "SL", title: "Sierra Leone" },
  { value: "SG", title: "Singapore" },
  { value: "SX", title: "Sint Maarten (Dutch part)" },
  { value: "SK", title: "Slovakia" },
  { value: "SI", title: "Slovenia" },
  { value: "SB", title: "Solomon Islands" },
  { value: "SO", title: "Somalia" },
  { value: "ZA", title: "South Africa" },
  { value: "GS", title: "South Georgia and the South Sandwich Islands" },
  { value: "SS", title: "South Sudan" },
  { value: "ES", title: "Spain" },
  { value: "LK", title: "Sri Lanka" },
  { value: "SD", title: "Sudan (the)" },
  { value: "SR", title: "Suriname" },
  { value: "SJ", title: "Svalbard and Jan Mayen" },
  { value: "SE", title: "Sweden" },
  { value: "CH", title: "Switzerland" },
  { value: "SY", title: "Syrian Arab Republic" },
  { value: "TW", title: "Taiwan" },
  { value: "TJ", title: "Tajikistan" },
  { value: "TZ", title: "Tanzania, United Republic of" },
  { value: "TH", title: "Thailand" },
  { value: "TL", title: "Timor-Leste" },
  { value: "TG", title: "Togo" },
  { value: "TK", title: "Tokelau" },
  { value: "TO", title: "Tonga" },
  { value: "TT", title: "Trinidad and Tobago" },
  { value: "TN", title: "Tunisia" },
  { value: "TR", title: "Turid" },
  { value: "TM", title: "Turkmenistan" },
  { value: "TC", title: "Turks and Caicos Islands (the)" },
  { value: "TV", title: "Tuvalu" },
  { value: "UG", title: "Uganda" },
  { value: "UA", title: "Ukraine" },
  { value: "AE", title: "United Arab Emirates (the)" },
  {
    value: "GB",
    title: "United Kingdom of Great Britain and Northern Ireland (the)",
  },
  { value: "UM", title: "United States Minor Outlying Islands (the)" },
  { value: "US", title: "United States of America (the)" },
  { value: "UY", title: "Uruguay" },
  { value: "UZ", title: "Uzbekistan" },
  { value: "VU", title: "Vanuatu" },
  { value: "VE", title: "Venezuela (Bolivarian Republic of)" },
  { value: "VN", title: "Viet Nam" },
  { value: "VG", title: "Virgin Islands (British)" },
  { value: "VI", title: "Virgin Islands (U.S.)" },
  { value: "WF", title: "Wallis and Futuna" },
  { value: "EH", title: "Western Sahara" },
  { value: "YE", title: "Yemen" },
  { value: "ZM", title: "Zambia" },
  { value: "ZW", title: "Zimbabwe" },
  { value: "AX", title: "Åland Islands" },
];
