// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: authapp.proto

package grpcauthapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for generating a token.
type TokenRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kid         *string                `protobuf:"bytes,1,opt,name=kid"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_authapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokenRequest) GetKid() string {
	if x != nil {
		if x.xxx_hidden_Kid != nil {
			return *x.xxx_hidden_Kid
		}
		return ""
	}
	return ""
}

func (x *TokenRequest) SetKid(v string) {
	x.xxx_hidden_Kid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TokenRequest) HasKid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TokenRequest) ClearKid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Kid = nil
}

type TokenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Kid *string
}

func (b0 TokenRequest_builder) Build() *TokenRequest {
	m0 := &TokenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Kid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Kid = b.Kid
	}
	return m0
}

// Response message for token generation.
type TokenResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_authapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *TokenResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TokenResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TokenResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

type TokenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token *string
}

func (b0 TokenResponse_builder) Build() *TokenResponse {
	m0 := &TokenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Token = b.Token
	}
	return m0
}

// Claims represents the authorization claims transmitted via a JWT.
type Claims struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Issuer      *string                `protobuf:"bytes,1,opt,name=issuer"`
	xxx_hidden_Subject     *string                `protobuf:"bytes,2,opt,name=subject"`
	xxx_hidden_Audience    []string               `protobuf:"bytes,3,rep,name=audience"`
	xxx_hidden_ExpiresAt   int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt"`
	xxx_hidden_NotBefore   int64                  `protobuf:"varint,5,opt,name=not_before,json=notBefore"`
	xxx_hidden_IssuedAt    int64                  `protobuf:"varint,6,opt,name=issued_at,json=issuedAt"`
	xxx_hidden_Id          *string                `protobuf:"bytes,7,opt,name=id"`
	xxx_hidden_Roles       []string               `protobuf:"bytes,8,rep,name=roles"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Claims) Reset() {
	*x = Claims{}
	mi := &file_authapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_authapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Claims) GetIssuer() string {
	if x != nil {
		if x.xxx_hidden_Issuer != nil {
			return *x.xxx_hidden_Issuer
		}
		return ""
	}
	return ""
}

func (x *Claims) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *Claims) GetAudience() []string {
	if x != nil {
		return x.xxx_hidden_Audience
	}
	return nil
}

func (x *Claims) GetExpiresAt() int64 {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return 0
}

func (x *Claims) GetNotBefore() int64 {
	if x != nil {
		return x.xxx_hidden_NotBefore
	}
	return 0
}

func (x *Claims) GetIssuedAt() int64 {
	if x != nil {
		return x.xxx_hidden_IssuedAt
	}
	return 0
}

func (x *Claims) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Claims) GetRoles() []string {
	if x != nil {
		return x.xxx_hidden_Roles
	}
	return nil
}

func (x *Claims) SetIssuer(v string) {
	x.xxx_hidden_Issuer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Claims) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Claims) SetAudience(v []string) {
	x.xxx_hidden_Audience = v
}

func (x *Claims) SetExpiresAt(v int64) {
	x.xxx_hidden_ExpiresAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Claims) SetNotBefore(v int64) {
	x.xxx_hidden_NotBefore = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Claims) SetIssuedAt(v int64) {
	x.xxx_hidden_IssuedAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Claims) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Claims) SetRoles(v []string) {
	x.xxx_hidden_Roles = v
}

func (x *Claims) HasIssuer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Claims) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Claims) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Claims) HasNotBefore() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Claims) HasIssuedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Claims) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Claims) ClearIssuer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Issuer = nil
}

func (x *Claims) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Subject = nil
}

func (x *Claims) ClearExpiresAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ExpiresAt = 0
}

func (x *Claims) ClearNotBefore() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_NotBefore = 0
}

func (x *Claims) ClearIssuedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_IssuedAt = 0
}

func (x *Claims) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Id = nil
}

type Claims_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Registered claims
	Issuer    *string
	Subject   *string
	Audience  []string
	ExpiresAt *int64
	NotBefore *int64
	IssuedAt  *int64
	Id        *string
	// Custom claims
	Roles []string
}

func (b0 Claims_builder) Build() *Claims {
	m0 := &Claims{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Issuer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Issuer = b.Issuer
	}
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Subject = b.Subject
	}
	x.xxx_hidden_Audience = b.Audience
	if b.ExpiresAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_ExpiresAt = *b.ExpiresAt
	}
	if b.NotBefore != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_NotBefore = *b.NotBefore
	}
	if b.IssuedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_IssuedAt = *b.IssuedAt
	}
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Roles = b.Roles
	return m0
}

// Request message for authentication.
type AuthenticateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_authapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *AuthenticateRequest) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AuthenticateRequest) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthenticateRequest) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

type AuthenticateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token *string
}

func (b0 AuthenticateRequest_builder) Build() *AuthenticateRequest {
	m0 := &AuthenticateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Token = b.Token
	}
	return m0
}

// Response message for authentication.
type AuthenticateResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,1,opt,name=user_id,json=userId"`
	xxx_hidden_Roles       []string               `protobuf:"bytes,2,rep,name=roles"`
	xxx_hidden_Subject     *string                `protobuf:"bytes,3,opt,name=subject"`
	xxx_hidden_Claims      *Claims                `protobuf:"bytes,4,opt,name=claims"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_authapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthenticateResponse) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *AuthenticateResponse) GetRoles() []string {
	if x != nil {
		return x.xxx_hidden_Roles
	}
	return nil
}

func (x *AuthenticateResponse) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *AuthenticateResponse) GetClaims() *Claims {
	if x != nil {
		return x.xxx_hidden_Claims
	}
	return nil
}

func (x *AuthenticateResponse) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *AuthenticateResponse) SetRoles(v []string) {
	x.xxx_hidden_Roles = v
}

func (x *AuthenticateResponse) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *AuthenticateResponse) SetClaims(v *Claims) {
	x.xxx_hidden_Claims = v
}

func (x *AuthenticateResponse) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthenticateResponse) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuthenticateResponse) HasClaims() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Claims != nil
}

func (x *AuthenticateResponse) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UserId = nil
}

func (x *AuthenticateResponse) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Subject = nil
}

func (x *AuthenticateResponse) ClearClaims() {
	x.xxx_hidden_Claims = nil
}

type AuthenticateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId  *string
	Roles   []string
	Subject *string
	// Claims contains the JWT claims.
	Claims *Claims
}

func (b0 AuthenticateResponse_builder) Build() *AuthenticateResponse {
	m0 := &AuthenticateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_UserId = b.UserId
	}
	x.xxx_hidden_Roles = b.Roles
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Subject = b.Subject
	}
	x.xxx_hidden_Claims = b.Claims
	return m0
}

// Request message for authorization.
type AuthorizeRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,1,opt,name=user_id,json=userId"`
	xxx_hidden_Claims      *Claims                `protobuf:"bytes,2,opt,name=claims"`
	xxx_hidden_Rule        *string                `protobuf:"bytes,3,opt,name=rule"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_authapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthorizeRequest) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *AuthorizeRequest) GetClaims() *Claims {
	if x != nil {
		return x.xxx_hidden_Claims
	}
	return nil
}

func (x *AuthorizeRequest) GetRule() string {
	if x != nil {
		if x.xxx_hidden_Rule != nil {
			return *x.xxx_hidden_Rule
		}
		return ""
	}
	return ""
}

func (x *AuthorizeRequest) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AuthorizeRequest) SetClaims(v *Claims) {
	x.xxx_hidden_Claims = v
}

func (x *AuthorizeRequest) SetRule(v string) {
	x.xxx_hidden_Rule = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AuthorizeRequest) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthorizeRequest) HasClaims() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Claims != nil
}

func (x *AuthorizeRequest) HasRule() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuthorizeRequest) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UserId = nil
}

func (x *AuthorizeRequest) ClearClaims() {
	x.xxx_hidden_Claims = nil
}

func (x *AuthorizeRequest) ClearRule() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Rule = nil
}

type AuthorizeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId *string
	Claims *Claims
	Rule   *string
}

func (b0 AuthorizeRequest_builder) Build() *AuthorizeRequest {
	m0 := &AuthorizeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_UserId = b.UserId
	}
	x.xxx_hidden_Claims = b.Claims
	if b.Rule != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Rule = b.Rule
	}
	return m0
}

// Response message for authorization.
type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_authapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AuthorizeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AuthorizeResponse_builder) Build() *AuthorizeResponse {
	m0 := &AuthorizeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_authapp_proto protoreflect.FileDescriptor

const file_authapp_proto_rawDesc = "" +
	"\n" +
	"\rauthapp.proto\x12\vgrpcauthapp\" \n" +
	"\fTokenRequest\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xd7\x01\n" +
	"\x06Claims\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\baudience\x18\x03 \x03(\tR\baudience\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"not_before\x18\x05 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tissued_at\x18\x06 \x01(\x03R\bissuedAt\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\b \x03(\tR\x05roles\"+\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x8c\x01\n" +
	"\x14AuthenticateResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12+\n" +
	"\x06claims\x18\x04 \x01(\v2\x13.grpcauthapp.ClaimsR\x06claims\"l\n" +
	"\x10AuthorizeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x06claims\x18\x02 \x01(\v2\x13.grpcauthapp.ClaimsR\x06claims\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\"\x13\n" +
	"\x11AuthorizeResponse2\xe7\x01\n" +
	"\x04Auth\x12>\n" +
	"\x05Token\x12\x19.grpcauthapp.TokenRequest\x1a\x1a.grpcauthapp.TokenResponse\x12S\n" +
	"\fAuthenticate\x12 .grpcauthapp.AuthenticateRequest\x1a!.grpcauthapp.AuthenticateResponse\x12J\n" +
	"\tAuthorize\x12\x1d.grpcauthapp.AuthorizeRequest\x1a\x1e.grpcauthapp.AuthorizeResponseB5Z3github.com/ardanlabs/service/app/domain/grpcauthappb\beditionsp\xe9\a"

var file_authapp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_authapp_proto_goTypes = []any{
	(*TokenRequest)(nil),         // 0: grpcauthapp.TokenRequest
	(*TokenResponse)(nil),        // 1: grpcauthapp.TokenResponse
	(*Claims)(nil),               // 2: grpcauthapp.Claims
	(*AuthenticateRequest)(nil),  // 3: grpcauthapp.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 4: grpcauthapp.AuthenticateResponse
	(*AuthorizeRequest)(nil),     // 5: grpcauthapp.AuthorizeRequest
	(*AuthorizeResponse)(nil),    // 6: grpcauthapp.AuthorizeResponse
}
var file_authapp_proto_depIdxs = []int32{
	2, // 0: grpcauthapp.AuthenticateResponse.claims:type_name -> grpcauthapp.Claims
	2, // 1: grpcauthapp.AuthorizeRequest.claims:type_name -> grpcauthapp.Claims
	0, // 2: grpcauthapp.Auth.Token:input_type -> grpcauthapp.TokenRequest
	3, // 3: grpcauthapp.Auth.Authenticate:input_type -> grpcauthapp.AuthenticateRequest
	5, // 4: grpcauthapp.Auth.Authorize:input_type -> grpcauthapp.AuthorizeRequest
	1, // 5: grpcauthapp.Auth.Token:output_type -> grpcauthapp.TokenResponse
	4, // 6: grpcauthapp.Auth.Authenticate:output_type -> grpcauthapp.AuthenticateResponse
	6, // 7: grpcauthapp.Auth.Authorize:output_type -> grpcauthapp.AuthorizeResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_authapp_proto_init() }
func file_authapp_proto_init() {
	if File_authapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authapp_proto_rawDesc), len(file_authapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authapp_proto_goTypes,
		DependencyIndexes: file_authapp_proto_depIdxs,
		MessageInfos:      file_authapp_proto_msgTypes,
	}.Build()
	File_authapp_proto = out.File
	file_authapp_proto_goTypes = nil
	file_authapp_proto_depIdxs = nil
}
